TrajectoryPlannerROS:
  max_vel_x: 0.42
  min_vel_x: 0.32
  max_vel_theta: 2.5
  min_in_place_vel_theta: 2.0

  acc_lim_theta: 0.5
  acc_lim_x: 1.0
  acc_lim_y: 2.5

  holonomic_robot: false

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.20
  latch_xy_goal_tolerance: false

