obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[1.4,0],[0.4,0.32],[-0.4,0.32],[-0.4,-0.32],[0.4,-0.32]]
footprint_padding: 0.3
#robot_radius: 1.5

#observation_sources: laser_scan_sensor point_cloud_sensor
#
#laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#
#point_cloud_sensor: {sensor_frame: laser, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}aa

static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan_filtered, inf_is_valid: true}

inflation:
        inflation_radius: 0.2
